# Generated by Django 5.1.7 on 2026-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livro_autores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
